### ISSUE TITLE
Related awesome lists

### ISSUE THREAD

**Issue by rshipp** [onlurking/awesome-infosec#2]
Hey!

There are more and more [infosec-related awesome lists](https://github.com/rshipp/awesome-malware-analysis#related-awesome-lists) on GitHub now, and I think it would be great if they all linked to each other so people could find them more easily. Would you be ok with adding a section like that to your list? I can submit a PR if you'd rather.

As a side note, there's also [this awesome badge](https://github.com/sindresorhus/awesome/issues/253), and you can add your list to that repo as well to get some more visibility.

**Comment by onlurking** [comment]
What a coincidence! lol. @rshipp 
I'm rewriting my awesome list right now and i came across your repository a few hours ago, and did the exactly same thing! actually, i just added a few links, i gonna push my changes to this repository later, well, you can track my changes [here](https://hackmd.io/s/V1GLSF0R) if you want update your 'related awesome lists' section right now too.
Oh, and thanks for the tip! :smile:

**Comment by rshipp** [comment]
You starring my list came up on my feed, which is how I stumbled upon your list. :smile: I already added it to my related lists section.

Also, that's a cool site, thanks for the link.
